import ManagerTemplate from "@/app/components/managerTemplate"
import MenuList from "../menulist"

export const metadata = {
   title: 'User | Ordering System',
   description: 'Generated by create next app',
}

type PropsLayout = {
   children: React.ReactNode
}

const RootLayout = ({ children }: PropsLayout) => {
   return (
       <ManagerTemplate title="User" id="User" menuList={MenuList}>
           {children}
       </ManagerTemplate>
   )
}

export default RootLayout
